apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql/mysql-server:8.0
          imagePullPolicy: IfNotPresent

          ports:
            - name: tpc
              protocol: TCP
              containerPort: 3306

          env:
            - name: MYSQL_PASSWORD
              valueFrom: 
               secretKeyRef: 
                name: mysql-secret
                key: MYSQL_PASSWORD

            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key: DATABASE_NAME
            
            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key: USERNAME

          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql

      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: db-pv-claim

